apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
spec:
#  ingressClassName: nginx # use only with k8s version >= 1.18.0
  rules:
  - host: grafana.nsm.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
