apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: product-page
  annotations:
    nsm.nginx.com/internal-route: "true"
spec:
#  ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
  rules:
  - host: productpage.demo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: productpage
          servicePort: 9080

