apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: driver
spec:
  ingressClassName: nginx # use only with k8s version >= 1.18.0
  rules:
  - host: driver.demo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: driver-allowed
          servicePort: 80
