apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: target-ts
spec:
  service: target-svc
  backends:
#  - service: target-v1-0
#    weight: 90
#  - service: target-v2-0
#    weight: 10
  - service: target-v2-1
    weight: 100

